apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullname-api
  namespace: my-micro-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullname-api
      tier: backend

  template:
    metadata:
      labels:
        app: fullname-api
        tier: backend

    spec:
      # nodeSelector:
      #   cpu-node: "2cpu"

      # tolerations:
      #   - key: "cpu-node"
      #     operator: "Equal"
      #     value: "2cpu"
      #     effect: "NoSchedule"

      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - fullname-api
              topologyKey: kubernetes.io/hostname

      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: fullname-api
          image: "{{ .Values.fullname.image }}:{{ .Values.fullname.tag }}"
          imagePullPolicy: {{ .Values.fullname.pullPolicy }}

          ports:
            - containerPort: 3000

          readinessProbe:
            httpGet:
              path: /fullname
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /fullname
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3

          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: MONGO_URI
              value: mongodb://appuser:apppassword@mongodb:27017/demo

---
apiVersion: v1
kind: Service
metadata:
  name: fullname-api
  namespace: my-micro-dev
spec:
  type: ClusterIP
  selector:
    app: fullname-api
    tier: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000