apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: my-micro-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: database

  template:
    metadata:
      labels:
        app: mongodb
        tier: database

    spec:

      # Previous scheduling logic (kept for reference)
      # nodeSelector:
      #   ram-node: "4gb"

      # tolerations:
      #   - key: "ram-node"
      #     operator: "Equal"
      #     value: "4gb"
      #     effect: "NoSchedule"

      affinity:

        # Prefer scheduling MongoDB on same node as Redis
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: redis
                topologyKey: kubernetes.io/hostname

        # Avoid nodes that run backend pods
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  tier: backend
              topologyKey: kubernetes.io/hostname

      containers:
        - name: mongodb
          image: mongo:7
          args:
            - "--auth"

          ports:
            - containerPort: 27017

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mongo-root-username

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mongo-root-password

          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
            - name: mongo-init
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc

        - name: mongo-init
          configMap:
            name: mongodb-init-script

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: my-micro-dev
spec:
  selector:
    app: mongodb
    tier: database
  ports:
    - port: 27017
      targetPort: 27017