apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: my-micro-dev
type: Opaque
stringData:
  mongo-root-username: root
  mongo-root-password: rootpassword
  mongo-app-user: appuser
  mongo-app-password: apppassword